config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to:'homes#top'
  devise_for :users

  resources :users, only:[:show,:edit,:update]

  resources :posts, only:[:new,:create,:index,:edit,:update,:destroy] do
    resources :comments, only: [:create, :show, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  get '/search', to: 'searchs#search'

  resources :groups do
    resource :group_users, only: [:create, :destroy]
    get '/search', to: 'searchs#group_search'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

end

app/models/group.rb
class Group < ApplicationRecord

  attachment :group_image
  has_many :group_users, dependent: :destroy

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  attachment :cooking_image

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :user_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :group_users, dependent: :destroy

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = @post.id
    @comment.save

    # redirect_to post_comment_path(id:post.id, post_id:post.id)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
    @post = Post.find(params[:post_id])

    # redirect_to post_comment_path(id:post.id, post_id:post.id)
  end

  private

  def comment_params
    params.permit(:comment)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save

    # redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy

    # redirect_to posts_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.save

    GroupUser.create(group_id:@group.id, user_id:current_user.id)

    redirect_to groups_path
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    redirect_to groups_path
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end

  def index
    @posts = Post.all
    @comment = Comment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:cooking_name, :cooking_image, :shop_name, :address, :comment)
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController

  def search
    @content1 = params["content1"]
    @content2 = params["content2"]
    @method1 = params["method1"]
    @method2 = params["method2"]

    if (@content1.present? && @content2.blank?)
      if @method1 == 'perfect'
        @posts = Post.where(cooking_name: @content1)
      else
        @posts = Post.where('cooking_name LIKE ?', '%'+@content1+'%')
      end

    elsif (@content1.blank? && @content2.present?)
      if @method2 == 'perfect'
        @posts = Post.where(address: @content2)
      else
        @posts = Post.where('address LIKE ?', '%'+@content2+'%')
      end

    elsif (@content1.present? && @content2.present?)
      if (@method1 == 'perfect' && @method2 == 'perfect')
        @posts = Post.where(cooking_name: @content1, address: @content2)

      elsif (@method1 == 'perfect' && @method2 == 'partial')
        @posts = Post.where(cooking_name: @content1).where('address LIKE ?', '%'+@content2+'%')

      elsif (@method1 == 'partial' && @method2 == 'perfect')
        @posts = Post.where('cooking_name LIKE ?', '%'+@content1+'%').where(address: @content2)

      else
        @posts = Post.where('cooking_name LIKE ? AND address LIKE ?', '%'+@content1+'%', '%'+@content2+'%')
      end

    end
  end

  def group_search
    @group_users = GroupUser.where(user_id: params[:group_id]) 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id:@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

end

private

def user_params
  params.require(:user).permit(:name, :user_image, :memo)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comments.html.erb
<% @post.comments.each do |comment| %>
  <div style="text-inline:center; border-top:1px solid #0000ff; padding-top:10px;">
    <%= link_to comment.user.name, user_path(comment.user.id) %>
    （<%= comment.created_at.strftime('%Y/%m/%d') %>）
    <% if comment.user == current_user %>
      <%= link_to "削除", post_comment_path(comment.post, comment), method: :delete, remote: true, class: 'btn btn-danger' %>
    <% end %>
    <br>
    <%= comment.comment %>
  </div>
<% end %>


<div style="margin-top:30px;">
  <%= form_with(url: post_comments_path(@post.id), remote: true) do |f| %>
    <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
    <%= f.submit "送信する", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/comments/_number.html.erb
<p>コメント数：<%= @post.comments.count %>件</p>

app/views/comments/create.js.erb
$('#comment_number_<%= @post.id %>').html("<%= j(render "comments/number", post: @post) %>");

$('#comment_buttons_<%= @post.id %>').html("<%= j(render "comments/comments", post: @post) %>");

app/views/comments/destroy.js.erb
$('#comment_number_<%= @post.id %>').html("<%= j(render "comments/number", post: @post) %>");

$('#comment_buttons_<%= @post.id %>').html("<%= j(render "comments/comments", post: @post) %>");

app/views/comments/show.html.erb
<h2 class="text-center", style="margin-top:50px;">投稿詳細</h2>

<div class="mx-auto", style="width:80%;">
  <table class="table">
    <thead>
      <tr class="text-center">
        <th>料理</th>
        <th>店名</th>
        <th>場所</th>
        <th>コメント</th>
        <th>投稿者</th>
      </tr>
    </thead>

    <tbody>
      <tr class="text-center">
        <th>
          <%= attachment_image_tag @post, :cooking_image, :fill, 200, 200 %><br>
          <%= @post.cooking_name %>
        </th>
        <th><%= @post.shop_name %></th>
        <th><%= @post.address %></th>
        <th><%= @post.comment %></th>
        <th>
          <%= link_to @post.user.name, user_path(@post.user.id) %><br>
          <%= attachment_image_tag @post.user, :user_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>

          <% if @post.user == current_user %>
            <%= link_to "編集", edit_post_path(@post.id), class: 'btn btn-success' %>
            <%= link_to "削除", post_path(@post.id), method: :delete, class: 'btn btn-danger' %>
          <% end %>
        </th>

        <th id="favorite_buttons_<%= @post.id %>">
          <%= render "favorites/favorites", post: @post %>
        </th>

        <th id="comment_number_<%= @post.id %>">
          <%= render "comments/number", post: @post %>
        </th>
      </tr>
  　</tbody>
  </table>
</div>

<div style="margin-left:10%; margin-right:10%;", id="comment_buttons_<%= @post.id %>">
　<%= render "comments/comments", post: @post %>
</div>

app/views/favorites/_favorites.html.erb
<% if user_signed_in? %>

  <% if post.favorited_by?(current_user) %>
    <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
      ♥<%= post.favorites.count %> いいね<br>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(post), method: :post, remote: true do %>
      ♡<%= post.favorites.count %> いいね<br>
    <% end %>
  <% end %>

<% else %>
  ♥<%= post.favorites.count %> いいね<br>

<% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @post.id %>').html("<%= j(render "favorites/favorites", post: @post) %>");

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @post.id %>').html("<%= j(render "favorites/favorites", post: @post) %>");

app/views/groups/edit.html.erb
<h2>コミュニティ編集</h2>

<%= form_with model:@group, local:true do |f| %>
  <h4>コミュニティ名</h4>
  <%= f.text_field :name %>

   <h4>コンセプト</h4>
  <%= f.text_field :introduction %>

  <h4>料理の写真</h4>
  <%= f.attachment_field :group_image %>

  <%= f.submit "変更を保存" %>
<% end %>

app/views/groups/index.html.erb
<h2 class="text-center", style="margin-top:50px;">コミュニティ一覧</h2>
<p class="text-center"><%= link_to "コミュニティ作成", new_group_path, class: 'btn btn-success' %></p>
<p class="text-center"><%= link_to "マイコミュニティ", group_search_path(current_user.id), class: 'btn btn-success' %></p>

<div class="mx-auto", style="width:80%;">
  <table class="table">
    <thead>
      <tr class="text-center">
        <th>コミュニティ名</th>
        <th>コンセプト</th>
        <th>メンバー数</th>
      </tr>
    </thead>

    <% @groups.each do |group| %>
      <tbody>
        <tr class="text-center">
          <th>
            <%= attachment_image_tag group, :group_image, :fill, 100, 100 %><br>
            <p><%= link_to group.name, group_path(group.id) %></p>
          </th>
          <th><%= group.introduction %></th>
          <th><%= group.group_users.count %></th>
          <th>
            <% if group.owner_id == current_user.id %>
              <%= link_to "編集", edit_group_path(group.id), class: 'btn btn-success' %>
              <%= link_to "削除", group_path(group.id), method: :delete, class: 'btn btn-danger' %>
            <% elsif group.group_users.exists?(user_id: current_user.id) %>
              <%= link_to "Retire this Group", group_group_users_path(group.id), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <%= link_to "Join this Group", group_group_users_path(group.id), method: :post, class: 'btn btn-success' %>
            <% end %>
          </th>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/groups/new.html.erb
<h2>コミュニティ作成</h2>

<%= form_with model:@group, local:true do |f| %>
  <h4>コミュニティ名</h4>
  <%= f.text_field :name %>
  <h4>コンセプト</h4>
  <%= f.text_field :introduction %>
  <h4>コミュニティ写真</h4>
  <%= f.attachment_field :group_image %>

  <%= f.submit '作成' %>
<% end %>

app/views/groups/show.html.erb
<div class="text-center", style="margin-top:50px;">
  <h2>コミュニティ詳細</h2>

  <% if @group.owner_id == current_user.id %>
    <p><%= link_to "コミュニティ編集", edit_group_path(@group), class: 'btn btn-success' %></p>
  <% end %>

  <div>
    <%= attachment_image_tag @group, :group_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <p>コミュニティ名：<%= @group.name %></p>
    <p>コンセプト：<%= @group.introduction %></p>
  </div>

  <% if @group.owner_id == current_user.id %>
    <%= link_to "編集", edit_group_path(@group.id), class: 'btn btn-success' %>
    <%= link_to "削除", group_path(@group.id), method: :delete, class: 'btn btn-danger' %>
  <% elsif @group.group_users.exists?(user_id: current_user.id) %>
    <%= link_to "Retire this Group", group_group_users_path(@group.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to "Join this Group", group_group_users_path(@group.id), method: :post, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h2>投稿編集</h2>

<%= form_with model:@post, local:true do |f| %>
  <h4>料理名</h4>
  <%= f.text_field :cooking_name %>

  <h4>料理の写真</h4>
  <%= f.attachment_field :cooking_image %>

  <h4>店名</h4>
  <%= f.text_field :shop_name %>

  <h4>場所</h4>
  <%= f.text_area :address %>

  <h4>コメント</h4>
  <%= f.text_area :comment %>

  <%= f.submit "変更を保存" %>
<% end %>

app/views/posts/index.html.erb
<h2 class="text-center", style="margin-top:50px;">投稿一覧</h2>

<div class="mx-auto", style="width:80%;">
  <table class="table">
    <thead>
      <tr class="text-center">
        <th>料理</th>
        <th>店名</th>
        <th>場所</th>
        <th>コメント</th>
        <th>投稿者</th>
      </tr>
    </thead>

    <% @posts.each do |post| %>
      <tbody>
        <tr class="text-center">
          <th>
            <%= attachment_image_tag post, :cooking_image, :fill, 200, 200 %><br>
            <p><%= post.cooking_name %></p>
          </th>
          <th><%= post.shop_name %></th>
          <th><%= post.address %></th>
          <th><%= post.comment %></th>
          <th>
            <%= attachment_image_tag post.user, :user_image, :fill, 60, 60, fallback: "no_image.jpg"%><br>
            <%= link_to post.user.name, user_path(post.user.id) %><br>

            <% if post.user == current_user %>
              <%= link_to "編集", edit_post_path(post.id), class: 'btn btn-success' %>
              <%= link_to "削除", post_path(post.id), method: :delete, class: 'btn btn-danger' %>
            <% end %>
          </th>

          <th id="favorite_buttons_<%= post.id %>">
            <%= render "favorites/favorites", post: post %>
          </th>

          <th>
            <p>コメント数：<%= post.comments.count %>件</p><br>
            <%= link_to "コメント一覧はこちら", post_comment_path(id:post.id, post_id:post.id) %>
          </th>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/posts/new.html.erb
<h2>新規投稿</h2>

<%= form_with model:@post, local:true do |f| %>
  <h4>料理名</h4>
  <%= f.text_field :cooking_name %>
  <h4>料理の写真</h4>
  <%= f.attachment_field :cooking_image %>
  <h4>店名</h4>
  <%= f.text_field :shop_name %>
  <h4>場所</h4>
  <%= f.text_area :address %>
  <h4>コメント</h4>
  <%= f.text_area :comment %>
  <%= f.submit '投稿' %>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>

<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>

  <%= attachment_image_tag @user, :user_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :user_image, placeholder: "プロフィール画像" %>

  <label for="inputMemo">Memo</label>
  <%= f.text_area :memo, autofocus: true, id:"inputMemo", placeholder:"メモ"%>

  <%= f.submit "変更を保存" %>
<% end %>

app/views/users/show.html.erb
<div class="text-center", style="margin-top:50px;">
  <h2>マイページ</h2>

  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user), class: 'btn btn-success' %></p>
    <p><%= link_to "コミュニティ関連", groups_path, class: 'btn btn-success' %></p>
  <% end %>

  <div>
    <%= attachment_image_tag @user, :user_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
    <p>ユーザー名：<%= @user.name %></p>
    <p>メモ：<%= @user.memo %></p>
  </div>

  <% if @user.id == current_user.id %>
    <%= link_to "新規投稿", new_post_path(@user), class: 'btn btn-success' %>
  <% end %>
</div>

<div class="mx-auto", style="width:80%;">
  <h2 class="text-center", style="margin-top:20px;">過去の投稿</h2>

  <table class="table">
    <thead>
      <tr class="text-center">
        <th>料理</th>
        <th>店名</th>
        <th>場所</th>
        <th>コメント</th>
      </tr>
    </thead>

    <% @posts.each do |post| %>
      <tbody>
        <tr class="text-center">
          <th>
            <%= attachment_image_tag post, :cooking_image, :fill, 200, 200 %><br>
            <%= post.cooking_name %>
          </th>
          <th><%= post.shop_name %></th>
          <th><%= post.address %></th>
          <th><%= post.comment %></th>
          <th>
            <% if post.user == current_user %>
              <%= link_to "編集", edit_post_path(post.id), class:'btn btn-success' %>
              <%= link_to "削除", post_path(post.id), method: :delete, class:'btn btn-danger' %>
            <% end %>
          </th>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>